###
FROM registry.access.redhat.com/ubi8/openjdk-17
COPY target/classes/* /deployments/classes/
COPY target/*.jar /deployments/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/deployments/app.jar"]
